### ISSUE TITLE
Typescript definition has incorrect module

### ISSUE THREAD

**Issue by PeterStaev** [bradmartin/nativescript-videoplayer#11]
This https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer.d.ts#L5 should be changed to be the name of the plugin. so it should be `nativescript-videoplayer` instead of just `videoplayer`

**Comment by bradmartin** [comment]
Fixed. Thanks @PeterStaev :+1: plugin has been updated on NPM.
