### ISSUE TITLE
Compilation failed on ios

### ISSUE THREAD

**Issue by patuku-roy** [bradmartin/nativescript-videoplayer#12]
When I'm running `tns build ios` .. compilation failed and show this error messages below:

```
Analyzing dependencies
Downloading dependencies
Using GoogleMaps (1.12.3)
Using IQKeyboardManager (4.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total
pods installed.
Processing node_modules failed. Exception: Pod install command failed. Error output: 2016-03-24 02:02:41.086 ruby[2692:42624] Failed to save project: "/Volumes/Data/<ProjectDir>/platforms/ios/Pods/Pods.xcodeproj"
```

I thought there is a problem with my internet connection so the pod can't be installed but after check my connection, everything is okay

And I'm using:

```
El Capitan 10.11.3
XCode 7.2
```

Any clue?

**Comment by bradmartin** [comment]
Don't know if this is an issue with this plugin @patuku-roy . Try uninstalling the video player plugin and see if your project builds. If it does then it might be the plugin but we don't use any pods with this plugin. It's all baked in controls provided by android/iOS. So this is likely not an issue with the video player. 

You might try pinging the slack channel for nativescript to see if someone more familiar with ios can help you with this.

**Comment by patuku-roy** [comment]
hi @bradmartin I think I found the problem, I think this is related to NS 1.7 file structure changes ... let me check first about this and I think so, this plugin does not use any pod at all, so maybe this is my bad, but thanks anyway for your fast reply, really appreciated.
