### ISSUE TITLE
Feature Request - Add option to overlay Android controls on VideoView

### ISSUE THREAD

**Issue by bradmartin** [bradmartin/nativescript-videoplayer#13]
Need to add an optional attribute to overlay the Media Controls on top of the Android *VideoView*. Could probably use this as the default and make it an optional attribute to not position it on top of the view. Attribute such as `android:anchorControls="false"` which would not anchor the controls.

**Comment by bnussey** [comment]
Hey @bradmartin we need this for our project so once we have it, will submit a pull request. One question, have you tried to mess around with floating any elements on top of the video? Noticed in Android you've got `this._android.setZOrderOnTop(true);` which forces the video to be on top of all other elements, despite z-index and a NativeScript AbsoluteLayout.. without this code though, it seems the video is not visible in the view. Would love to hear your comments if you've messed around with it, if not, all good, will submit pull request once it's all tested.

**Comment by bradmartin** [comment]
There was a bug with previous version of NativeScript android and the layer
types that's why I had to hard code the setz(). It should be fixed in the
next release which is scheduled for this week, hopefully today or tomorrow.
Then you should be able to position elements on top of the view. Others
were doing this prior to the layer bug. Hope that helps.

**Comment by Ivshti** [comment]
@bradmartin sorry for the off-topic, but this is highly important, so I want another confirmation

This means that the new {N} finally has fixed the layering bug, and we are going to be able to overlay elements over video like in 1.4?

**Comment by bradmartin** [comment]
You should, but I have not confirmed this. You can try using the @next
release the team publishes to see if it's fixed before the release since
the actual PR was made weeks ago. I haven't had time to do this.

**Comment by bnussey** [comment]
@bradmartin cant thank you enough for this information, really appreciate it, and apologies for the off topicness as well.

**Comment by bradmartin** [comment]
using the `controls` attribute anchors the media controls to the view as expected.
