### ISSUE TITLE
doc: Documentation of using this plugin with angular 2

### ISSUE THREAD

**Issue by aksharpatel47** [bradmartin/nativescript-videoplayer#15]
I'm using nativescript with angular for my next application. It has a lot of videos to play and I tried to integrate this plugin, but couldn't get it to work. I'm pretty sure that there might be some changes in the syntax when we're using this with angular. I would like to help out, in any way I can, to get this plugin documented and working great with nativescript and angular projects. Let me know how I can be of help.

**Comment by bradmartin** [comment]
Hi @aksharpatel47 - I haven't started using ng2 with NativeScript yet so I'm not 100% certain. You are right, there are a few things to do to make it work. Someone mentioned this on the CardView plugin to get it working with ng2 apps:

      import {registerElement} from "nativescript-angular/element-registry";
      registerElement("CardView", () => require("nativescript-cardview").CardView);

So that might be of help with the VideoPlayer.  You could try replacing the mentions of *CardView* with **VideoPlayer** since that's the class in this plugin. Hope that helps some, if so and you would like you can add some info to the README for others :+1:  Either way, let me know what happens.

**Comment by pn222ez** [comment]
Hi!
I've tried this with Angular. Can't get it to work. Is it possible to make it work?

**Comment by bradmartin** [comment]
It's definitely possible :) it's just a matter or registering it correctly and making sure it's added to your project correctly. Are you importing and registering like the sample snippet I posted previously?

**Comment by pn222ez** [comment]
Yes and in the template same as your example in readme.

**Comment by NathanWalker** [comment]
@pn222ez could you post your component or bootstrap file?

This should work:
```
// somewhere at top of your component or bootstrap file
import {registerElement} from "nativescript-angular/element-registry";
registerElement("VideoPlayer", () => require("nativescript-videoplayer").Video);


Then you can use:
<VideoPlayer
            src="~/videos/small.mp4"
            (loaded)="videoplayerLoaded($event)" 
            (finished)="videoFinished($event)" 
            autoplay="true" 
            height="300"></VideoPlayer>
```

**Comment by pn222ez** [comment]
@NathanWalker @bradmartin It works! Thank you!

**Comment by pn222ez** [comment]
Is it a problem to load a video from a variable. Can't get this to work:

```
<VideoPlayer
          *ngIf="video"
          src="{{ video }}"
          autoplay="true" 
          height="300"></VideoPlayer> 
```
This works:
```
<VideoPlayer
          *ngIf="video"
          src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
          autoplay="true" 
          height="300"></VideoPlayer>
```

**Comment by MilosStanic** [comment]
@pn222ez 

try

```
<VideoPlayer
          *ngIf="video"
          [src]="video"
          autoplay="true" 
          height="300"></VideoPlayer>
```

**Comment by pn222ez** [comment]
@MilosStanic It doesn't work either.

**Comment by robertonic** [comment]
I've tried Nathan Walker's suggestion for use with Angular and it works for web hosted files.  Thanks. 

However if I try to use a local file it never plays. 

I have the file stored in app/videos  and access it using 

src="~/videos/my_video.mp4"

Every time though I get the message "Can't play this video".  

The mp4 plays without problems in other players. 

As a test I set autoplay to false and in the player it shows the current time for the vidoe duration so I'm sure it is finding it. 

I've tried changing the video format to AVI that doesn't help. 

Any ideas?

**Comment by bradmartin** [comment]
That error is an android thing. I have not taken the time to exactly figure
out what files will work and dont work. I encountered this issue during
initial development and I forget a lot of the research I did. I was
researching because of remote videos, YouTube mainly. I had valid URLs and
kept receiving that error message and it was how Google wanted it to work
if I remember and that's why they have a YouTube sdk now. So as for local
videos you migjt try joining the slack channel and ping this there and see
if anyone knows more about the specifics.

**Comment by robertonic** [comment]
The problem seems to be due to the format of the video file and not whether it's local or remote. 

After trying various formats I've found an option that works for my local videos. The important thing is to create videos with a constant framerate.  Using a variable frame rate creates a video the Android player cannot play.

**Comment by bradmartin** [comment]
Nice to know. Thanks. If anyone wants to add some extra info to the README
that would be great. If not I'll do it.

**Comment by handlebarcreative** [comment]
For those having issues with playing files downloaded to the device, maybe take a peek at line 18 in video-source.ios.js or line 46 in video-source.android.js.

If you're using "~/" in your video path, its expecting the video to live within the fs.knownFolders.currentApp().path.  

In my application, my video lives within the fs.knownFolders.documents() directory, which was causing me grief.

Sorry that this isn't angular2 specific, but I think this could solve some issues mentioned above with both a) using variables, and b) using video sources prefixed with "~/".

JS:
```
var documents = fs.knownFolders.documents();
var videoPath = "~/myVideo.mp4";
videoPath = videoPath.replace("~/", "");
var fullPath = "file://" + fs.path.join(documents.path, videoPath);
viewModel.set("videoSrc", fullPath);
```

XML:
```
<VideoPlayer:Video src="{{videoSrc}}" finished="videoFinished" autoplay="true" height="300" />
```

**Comment by tomylee001001** [comment]
Hi,
I'm also using nativescript with angular for my application. and when i use the below i can play video in my aplication.

> import {registerElement} from "nativescript-angular/element-registry";
> registerElement("VideoPlayer", () => require("nativescript-videoplayer").Video);

But i also need to use api for my aplication. and if i'm trying to use the api with the code below

> import { Video } from 'nativescript-videoplayer';

But whenever i write that code and build i get the error below. do i using the code wrong or should i do something else for using the api.

> node_modules/nativescript-videoplayer/index.d.ts(1,15): error TS2306: File 'C:/n
> ativework/platform1/node_modules/nativescript-videoplayer/videoplayer.d.ts' is n
> ot a module.
> 
> node_modules/nativescript-videoplayer/videoplayer.d.ts(9,5): error TS2439: Impor
> t or export declaration in an ambient module declaration cannot reference module
>  through relative module name.
> 
> node_modules/nativescript-videoplayer/videoplayer.d.ts(9,34): error TS2307: Cann
> ot find module './video-source/video-source'.

**Comment by bradmartin** [comment]
So yea you have some typescript issues. Nothing major. It should still work
but the definitions might need some improvement.

**Comment by tomylee001001** [comment]
if there is nothing major is there any way to reach api as with the current version or do i need to something else for it.

**Comment by bradmartin** [comment]
Does the project still build? If not you need to modify your tsconfig.json file and change the noEmitOnError to false. If the project does build then it's just that your IDE isn't picking up the definition or there's an issue with the definition. Let me start a new project and see if it works for me. I thought I had it fixed but I'll confirm and let you know.

**Comment by tomylee001001** [comment]
thanks for the fast reply.When i set noEmitOnError to false everything work like charm.
THanks for your help

**Comment by bradmartin** [comment]
Welcome. It's just typescript related. When that's set to true all ts code has to pass compiler warnings. Setting to false will still transpile to js.

**Comment by Mubashir-Mohamed** [comment]
hi,
I am building an app using angular nativescript .  I want a videoplayer  in my app, i followed your instructions but still, it is not even showing the player.
I am working on ios. Any thoughts on that.
Thanks in advance

**Comment by job111** [comment]
how can i display a video i chose from the gallery
