### ISSUE TITLE
Bind Video Source

### ISSUE THREAD

**Issue by nikolal** [bradmartin/nativescript-videoplayer#16]
How can I bind Video src???

// Example 1 WORKING

`  
<VideoPlayer:Video  loaded="videoplayerLoaded"
                            finished="videoFinished"
                            autoplay="false"
                            height="200"
                             src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" />
`

// Example 2 NOT WORKING

`
         <VideoPlayer:Video  loaded="videoplayerLoaded"
                            finished="videoFinished"
                            autoplay="false"
                            height="200"
                            src="{{ video }}" />
`

**Comment by bradmartin** [comment]
What's your JS code for the model?

**Comment by nikolal** [comment]
```
var onChildEvent = function(result) {
      var matches = [];

      if (result.type === "ChildAdded") {
        viewModel.push(result.value);
      }
      else if (result.type === "ChildRemoved") {
        matches.push(result);
        matches.forEach(function(match) {
          var index = viewModel.indexOf(match);
          viewModel.splice(index, 1);
        });
      }
    };
```

I am using Firebase. My data have 10 properties, one of them is "video". All the others are working.

**Comment by nikolal** [comment]
Does anyone else have similar problem. This is article screen so my  JS code is very simple.

```
exports.loaded = function(args) {
  var page = args.object;
  page.bindingContext = page.navigationContext;
};
```

I am passing navigationContext from ListView on another screen.

```
exports.goToArticle = function(args) {
  var itemView = args.object;
  var item = itemView.bindingContext;

  var navigationContext = {
    moduleName: "shared/components/article-card/article-card",
    context: item,
    animated: false
  };

  frameModule.topmost().navigate(navigationContext);
};
```
If I log page.bindingContext I am getting proper data.

```
{
  "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor leo non viverra vulputate",
  "title": "Chet Lemon Wins It All",
  "info": "Short explanation about the article",
  "image": "http://mlb.mlb.com/det/images/ballpark/480x200_main.jpg",
  "bodyspan": "Lorem Ipsum ",
  "video": "https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
}
```


If you worked with AngularJS, there were some issues with trusting URLs. They offered $sce module as a fix. Could my issue be something similar?

$sce.trustAsResourceUrl(recordingUrl);

https://docs.angularjs.org/api/ng/service/$sce

Or maybe my URL doesn't get on time to be used by the player???

**Comment by bradmartin** [comment]
Im on vacation or I'd check this out. I forget if there is a change event
for the video player. I think there is but don't recall. You can check the
source for the change event but it should work.

**Comment by nikolal** [comment]
Thx for your response. I was dealing with Firebase new update these days so I didn't have time to check it out yet. I will post here when I find the problem.

**Comment by bradmartin** [comment]
You might want to join the nativescript slack community (if you haven't already) and see if anyone else has any issues binding the source. You can get some great instant feedback on the different channels there :smile:

**Comment by nikolal** [comment]
I am already there. I will close this for now, since we decided to use webview to be able to add some additional HTML content from website.

Thanks  once more for your help.
