### ISSUE TITLE
Feature Request - VAST Enabled

### ISSUE THREAD

**Issue by tsaboin** [bradmartin/nativescript-videoplayer#17]
It'll be nice to have VAST Ads url enabled.

**Comment by bradmartin** [comment]
Do you have a link so I can read more info about this? Thanks.

**Comment by tsaboin** [comment]
https://en.m.wikipedia.org/wiki/Video_Ad_Serving_Template 

This is the fastest I can lay my hands on.

**Comment by bradmartin** [comment]
I don't think this plugin should incorporate the VAST ability. According to Google there is a SDK that handles interactive media and that's the recommended way to do so. This plugin uses the already available native controls and does not bring in any external dependencies so it remains lightweight, if we add the SDK it adds to the overall app size. You might want to join the nativescript slack community and see if anyone has interest in developing a plugin for the IMA Android SDK. https://developers.google.com/interactive-media-ads/docs/sdks/android/

**Comment by tsaboin** [comment]
Noted. Thanks..
