### ISSUE TITLE
finished event not implemented in iOS?

### ISSUE THREAD

**Issue by handlebarcreative** [bradmartin/nativescript-videoplayer#21]
Might be an oversight on my behalf, but I don't think the finished event is plugged in for iOS.
I see code implemented in it for Android, and can confirm it works properly there.  I don't see anything written for iOS, and also cannot get it to fire in iOS at all.

Feel free to close this issue if I've clearly overlooked something.

**Comment by handlebarcreative** [comment]
@bradmartin  - I've been able to get this working by fiddling with the JS in my node_modules dir.  I'd issue a pull request, but I'm having difficulty getting the project running for local dev, and I'm also a total noob to TypeScript.

In the constructor of the Video class for videoplayer.ios, I've added the following code, which fires  the finished event correctly.

If any other contributor could assist in implementing this, that'd be great.

```
var self = this;

if (this.finishedCallback) {
    //console.log("yo, finished callback exists");
    var nsCenter = NSNotificationCenter.defaultCenter();
    nsCenter.addObserverForNameObjectQueueUsingBlock(AVPlayerItemDidPlayToEndTimeNotification, null, null, function() {
        self._emit(common.Video.finishedEvent);
    });
}
```

**Comment by bradmartin** [comment]
Awesome. I can handle the typescript for this and test to confirm all is
fine. Thanks

**Comment by bnussey** [comment]
hey @handlebarcreative just adding this to a pull request now.. for testing purposes, what was your local code to link up the finishedCallback?

**Comment by bnussey** [comment]
this is now working in my latest PR

**Comment by handlebarcreative** [comment]
hey @bnussey - I wasn't doing anything fancy for the finished callback.  In my xml just:
`<VideoPlayer:Video src="~/myvideo.mp4" finished="videoFinished" autoplay="false" height="300" width="300" />`

**Comment by bnussey** [comment]
Thanks @handlebarcreative my issue was i was using Angular2 but figured it all out, appreciate your assistance.
