### ISSUE TITLE
destroy public method needed

### ISSUE THREAD

**Issue by handlebarcreative** [bradmartin/nativescript-videoplayer#22]
Navigating back and forth from pages with a video player within them can cause a memory leak.
A destroy method, which can be called on navigatedFrom within an app's page would help.

Here's an example of one for iOS (which will also remove the loop callback)
Again, sorry for JS only version.

```javascript
Video.prototype.destroy = function() {

    if (this.finishedCallback) {
        var nsCenter = NSNotificationCenter.defaultCenter();
        nsCenter.removeObserverNameObject(AVPlayerItemDidPlayToEndTimeNotification, null, null);
    }

    this._player.pause();
    this._player = null; //de-allocates the AVPlayer
    this._playerController = null;

};
```

**Comment by bradmartin** [comment]
@bnussey - think you can add this for iOS? Looks like you just make sure the Observer is removed and null out the player. Should be straightforward TS conversion. Let me know if you need help on the TS side. I suppose just like @handlebarcreative suggested for name: `destroy` is good for me.

**Comment by bnussey** [comment]
Hey @bradmartin yep absolutely I will do this.

**Comment by bradmartin** [comment]
I've got a big refactor ready, but one snag I'm hitting with the plugin. Once you submit the PR I'll get it all synced up with the refactor to be 100% TS READY!
