### ISSUE TITLE
Can't play the video if i set src inside the subscribe

### ISSUE THREAD

**Issue by tomylee001001** [bradmartin/nativescript-videoplayer#26]
Hi,
in my app i need to get video informations (video path  etc) from my server and with that informations i want to play the video.But even though i can set the video src in the subcribe part of the code video dont play and player act as there is no src setted (even if i call outside functions inside of subcribe code blok to set src it doesnt work).but if i set src outside of the subcribe code block it work perfectlly.

ngOnInit() {
            this._videoPlayer = <Video>this.playerid.nativeElement;
           --if i set videoplayer src right here video works>>
            this._onlinetvService.LoadVideobyid(this.id)
                    .subscribe
            (loadedvideo => {
                
            this._video_item=loadedvideo as Video_Item;
	    this._videoPlayer.src=Config.hostUrl+this._video_item.path;<<if i set src here even if i see that src was set video doesnt play>> 
           if(this._video_item.slides.length>0)
            {
                this.slide_url=this._video_item.slides[0].pic_url;
            }
            this.index_list=this._video_item.indexes;
            this.trackVideoCurrentPosition();

            console.log(" toplam indexes : "+this._video_item.indexes.length);
            console.log(" toplam slides : "+this._video_item.slides.length);
            
            
            
            console.log(" video url : "+Config.hostUrl+this._video_item.path);
            },
            (error) => alert("Hata."+error)
                );

            

    }

thanks.

**Comment by bradmartin** [comment]
You ever get this working? It might some zone issue. I don't do much ng2 sorry.

**Comment by tomylee001001** [comment]
i havent find a solution for this yet but if i ever able to upgrade my app to the new version i will try again. Right now (even though i don't like it ) i am getting my video item when user tap the video in my galery page before navigate and writing that video item to my global config to read for the player.

**Comment by kazemihabib** [comment]
try set src in `ngZone.run`:
```
import {NgZone} from "@angular/core";
export class playerPage {
   constructor(private _ngZone: NgZone){}
    this._ngZone.run(() => {
         //set src here
     });
}
```

**Comment by bradmartin** [comment]
Should work fine with ngZone from everything I've read and @kazemihabib comment above. This has come up on the NS slack channel before also and the solution was the zone stuff (ng2 isn't my specialty yet) 👍
