### ISSUE TITLE
TS-NG2: Cannot find module './video-source/video-source'.

### ISSUE THREAD

**Issue by jahidshohel** [bradmartin/nativescript-videoplayer#27]
I was following the demo app, and I am getting this error when trying to get hold of the player -

> myPause(e:any) {
        let videoPlayer = topmost().getViewById('nativeVideoPlayer');
        this.doPause(videoPlayer)
    }
    doPause(videoPlayer:Video) {
        videoPlayer.pause();
    }

And the error I am getting is -

> Found peer TypeScript 1.8.10
app/components/tabs/tab3/tab3.component.ts(27,22): error TS2345: Argument of type 'View' is not assignable to parameter of type 'Video'.
  Property 'src' is missing in type 'View'.

> node_modules/nativescript-videoplayer/index.d.ts(1,15): error TS2306: File '/Users/jahid/Development/temp/native_script/ns-learning/node_modules/nativescript-videoplayer/videoplayer.d.ts' is not a module.

> node_modules/nativescript-videoplayer/videoplayer.d.ts(9,5): error TS2439: Import or export declaration in an ambient module declaration cannot reference module through relative module name.

> node_modules/nativescript-videoplayer/videoplayer.d.ts(9,34): error TS2307: Cannot find module './video-source/video-source'.

**Comment by jahidshohel** [comment]
I have tried changing `onEmitError` to false, it builds, but at run time fails with error -

> 08-13 08:55:50.450 27132 27132 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
08-13 08:55:50.450 27132 27132 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
08-13 08:55:50.450 27132 27132 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
08-13 08:55:50.450 27132 27132 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:713)
08-13 08:55:50.450 27132 27132 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:694)
08-13 08:55:50.450 27132 27132 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:684)

**Comment by bradmartin** [comment]
Your first error is a TS issue you have, the other TS issues I'll update
the definitions later on to fix those. And your current error looks like
bad code is getting called.

**Comment by bradmartin** [comment]
I was able to fix a few things with the demo and I have it running successfully on Android devices. For now, ignore the TS errors. I need to set a lot of time to get all of those cleaned up and fixed without breaking the plugin. As for the runtime error, you will likely need to do a new build and run that version, so uninstall any old versions on your device/emulator before running the new build on the device.

**Comment by matart15** [comment]
same issue with 1.0.5 and 1.0.6

**Comment by bradmartin** [comment]
Should be fixed with https://github.com/bradmartin/nativescript-videoplayer/releases/tag/1.0.9

**Comment by matart15** [comment]
thank you

**Comment by bradmartin** [comment]
All of these errors/warnings should be resolved with latest release. Closing for now, if needed please reopen.

**Comment by pbgc** [comment]
@JillevdW @bradmartin I'm having the exact same error
