### ISSUE TITLE
Can't get getCurrentTime after the 1.0.3 version update

### ISSUE THREAD

**Issue by tomylee001001** [bradmartin/nativescript-videoplayer#30]
Hi,
i am using nativescript-angular 2 after updating the plugin i am started to not get getCurrentTime from the api and no error on the console everything else work perfectly. i mean i can play/pause or seek without any problem.

**Comment by bnussey** [comment]
Hey @tomylee001001 this is working for me.. have you updated to the latest `tns-ios` this was causing issues with the getCurrentTime

**Comment by bnussey** [comment]
And is this Android or iOS?

**Comment by tomylee001001** [comment]
@bnussey  right now i am using it with android. after my package.json as follows ;

"dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/platform-server": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "email-validator": "^1.0.4",
    "nativescript-angular": "next",
    "nativescript-cardview": "^1.1.11",
    "nativescript-imagepicker": "0.0.6",
    "nativescript-permissions": "^1.1.2",
    "nativescript-pulltorefresh": "^1.1.7",
    "nativescript-splashscreen": "^2.1.0",
    "nativescript-telerik-ui": "^1.3.1",
    "nativescript-videoplayer": "^1.0.3",
    "reflect-metadata": "^0.1.5",
    "rxjs": "5.0.0-beta.6",
    "tns-core-modules": "next",
    "zone.js": "^0.6.12"
  },

**Comment by bnussey** [comment]
Can you post your tns info?

**Comment by tomylee001001** [comment]
All NativeScript components versions information
┌──────────────────┬───────────────────────┬────────────────┬───────────────┐
│ Component        │ Current version       │ Latest version │ Information   │
│ nativescript     │ 2.2.1                 │ 2.2.1          │ Up to date    │
│ tns-core-modules │ 2.3.0-2016-08-25-3961 │ 2.2.1          │ Up to date    │
│ tns-android      │ 2.2.0                 │ 2.2.0          │ Up to date    │
│ tns-ios          │                       │ 2.2.1          │ Not installed │
└──────────────────┴───────────────────────┴────────────────┴───────────────┘

**Comment by tomylee001001** [comment]
After working on it for so much i have finally solve the problem. Before the update i was using this code to get current time,

var time_nr=parseInt(this._videoPlayer.getCurrentTime()); 

But after the update this code started to not work after trial and error i finally able to get the current time with this code

var time_=this._videoPlayer.getCurrentTime;
var time_nr=parseInt(time_.toString());

i dont understand whats changed to get this problem on android and i havent tested this code on ios but for now i was able to get the current time again.
