### ISSUE TITLE
Can't play this video message

### ISSUE THREAD

**Issue by NNieto** [bradmartin/nativescript-videoplayer#32]
I tried with s3 url and not works, a local file neither. I prove another url and still not works. can u help me? thanks.

**Comment by bradmartin** [comment]
Assuming this is android? If so, android is very picky about videos. Try
with the demo videos and see if it works. If so then there's no issue with
the plugin. I don't know all the specifics about why android is so
difficult with the videos it will play. The two in the demo should work
fine though.

**Comment by NNieto** [comment]
@bradmartin Thanks man

**Comment by bradmartin** [comment]
Yea android video sucks sometimes :) took me awhile to learn that. Just
check the video encoding and format and I'm sure there might be a service
that you can upload it to that will check it works on android or not

**Comment by NNieto** [comment]
@bradmartin Perfect, I'll check it and change my encoding format. Thanks
