### ISSUE TITLE
timeupdate event

### ISSUE THREAD

**Issue by scemis** [bradmartin/nativescript-videoplayer#33]
Hi Martin,
Is it possible to use somthing like timeupdate event in videojs player : [http://docs.videojs.com/docs/api/player.html#Eventstimeupdate]

**Comment by bradmartin** [comment]
You should be able to get the current time and duration of the video. So
yes, watch the current time for changes. Several ways but a simple solution
is to use setInterval() and then check if it's changed after x time.

**Comment by scemis** [comment]
Martin,

Thanks a lot for your reply.
I thought about the same technique.
I'm going to use setTimeout() function.

I thionk you can close that issue.

Thanks a lot.
