### ISSUE TITLE
error TS2307: Cannot find module './videoplayer'.

### ISSUE THREAD

**Issue by aquiintac** [bradmartin/nativescript-videoplayer#35]
I'm not sure if it is related to the error "Cannot find module './video-source/video-source'".

When I tried running my app i got the following error:

app/pages/video/videoplayerpage.ts(6,9): error TS2305: Module '"C:/sampleapp/node_modules/nativescript-videoplayer/index"' has no exported member 'Video'.

/node_modules/nativescript-videoplayer/index.d.ts(1,15): error TS2307: Cannot find module './videoplayer'.

**Comment by scemis** [comment]
I had the same issue.
I found that some .ts files are missed in 'node_modules\nativescript-videoplayer' folder:

- videoplayer-common.ts
- videoplayer.android.ts
- videoplayer.ios.ts

I just get them directly from github and put in that folder 'node_modules\nativescript-videoplayer' folder;

Missed files:
- https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer-common.ts
- https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer.android.ts
- https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer.ios.ts

**Comment by bradmartin** [comment]
Sorry about those issues, probably just lost in some of the recent updates. I'll try to review and make sure it's fixed with next publish.

**Comment by bnussey** [comment]
Which version are you on?

**Comment by scemis** [comment]
I use the latest one, downloaded today.

**Comment by scemis** [comment]
By the way this version works just well for me, I even use emulator to test (local & remote videos).
Brad, thanks a lot!

**Comment by bradmartin** [comment]
@scemis all @bnussey lately 👍

**Comment by bnussey** [comment]
The .ts files are intentionally ignored for the npm package as they're not required. This is done to reduce package size.

**Comment by bradmartin** [comment]
Found part of the issue (typings key on package.json), the definitions should be on npm - but yea the source TS files don't because they aren't needed. The definition files should be and that resolves the TS compiler so no warnings are thrown.

**Comment by bradmartin** [comment]
The 1.0.8 release has the typings key in the package.json which will help resolve the TS pieces. So should be no issue going forward with the package.

**Comment by guru1966** [comment]
I downloaded the latest and still get the following error:

node_modules/nativescript-videoplayer/index.d.ts(1,15): error TS2307: Cannot find module './videoplayer'.
app/video-model.ts(7,10): error TS2305: Module '"/Users/...../Developement/terraceoapps/Sagotecken/node_modules/nativescript-videoplayer/index"' has no exported member 'Video'.
app/video.ts(8,10): error TS2305: Module '"/Users/....../Developement/terraceoapps/Sagotecken/node_modules/nativescript-videoplayer/index"' has no exported member 'Video'.

**Comment by bradmartin** [comment]
I may just rewrite the definitions by hand to make it work better.

**Comment by aquiintac** [comment]
i'm still getting the same error as @guru1966 after downloading the updated version.

thank you @bradmartin, will wait for the updated files.

**Comment by bradmartin** [comment]
Yea I'm taking a look now. Will figure out a better solution 👍

**Comment by matart15** [comment]
same issue with 1.0.8

**Comment by bradmartin** [comment]
Should be fixed with 1.0.9 just published, let me know if you still have warnings/errors. I've ran it successfully with a new demo app and no TS errors/warnings

**Comment by matart15** [comment]
Thank you.
It compiled on android

**Comment by aquiintac** [comment]
hi @bradmartin it's working now. I tried running the demo. Thank you very much! 
Although when i clicked on stop and then play again, the video doesn't play. But that's another story, I'll check that one out.

hi @matart15 you can try to uninstall and install nativescript-videoplayer.


![image](https://cloud.githubusercontent.com/assets/18011698/18904685/fa37c0b8-8591-11e6-83eb-bfc746bd028c.png)

**Comment by matart15** [comment]
@aquiintac Thank you.
I tried again from zero like this.
```
$ rm -rf nativescript-videoplayer
$ git clone https://github.com/bradmartin/nativescript-videoplayer.git
```
 and got same error.


However deleting only `node_modules` and `platform` and reinstalling worked.
maybe some kind of cache related problem.

**Comment by bradmartin** [comment]
Stop on android works. Check the readme

**Comment by aquiintac** [comment]
i just read it... sorry about that hahaha. got it :)

**Comment by bradmartin** [comment]
All good. I might have forgotten to publish the def file. If so I'll
release a fix later today.

**Comment by guru1966** [comment]
Demo not working for me, still same error as @matart15.
Deleting only node_modules and platform and reinstalling did not work for me.
Tested on Android emulator, maybe worked for some of you on Android device?

**Comment by bradmartin** [comment]
So @guru1966 still not working for you? I would manually uninstall the app from the device/emulator. Clone the repo, path to demo folder, build the .apk and then `run` it that should work.

**Comment by bradmartin** [comment]
The package is published correctly and all of the TS warnings/errors should be resolved, I've tested multiple times and was successful. It's likely an issue with the old .apk not being removed from the device, even though you rebuild and run sometimes you need a manual uninstall to make Android straighten out. I'm closing this issue for now since the TS warnings/errors are resolved. @guru1966 if you continue having issues with the demo project running please open a new issue with some error logs. Thanks everyone 👍
