### ISSUE TITLE
Failed to find module with absolute path, crash in DEMO on Android

### ISSUE THREAD

**Issue by guru1966** [bradmartin/nativescript-videoplayer#37]
Hello !

I have done the following:
$ git clone https://github.com/bradmartin/nativescript-videoplayer.git
$ cd nativescript-videoplayer/demo
$tns install
$ tns --version
2.3.0
$tns run android

Here is crash log. I could repeatedly reproduce this crash on emulator or device no matter what I do.
Something you see I am doing wrong?

![device-2016-09-29-201021](https://cloud.githubusercontent.com/assets/4431497/18966416/597da1ec-8681-11e6-9fc5-1c55e0642d21.png)

**Comment by bradmartin** [comment]
Well it shouldn't be looking in your `app/` folder for the module, it's in node_modules. Did you change the path on the `<Page xmlns="">` pointing to the plugin?

**Comment by bradmartin** [comment]
Another thing I never run `tns install` - I run `build` then `run` or `livesync` to start working.

So it's possible something went wrong during that step and the module never was installed correctly.

**Comment by guru1966** [comment]
Ok, following steps were done:
$ rm -rf nativescript-videoplayer
$ git clone https://github.com/bradmartin/nativescript-videoplayer.git
$ cd nativescript-videoplayer/demo
$adb uninstall org.nativescript.demo
Success
$ tns build android
$ tns build run

Still same crash as before.

In my main-page.xml I have the following:
<Page 
  xmlns="http://schemas.nativescript.org/tns.xsd" 
  xmlns:Video="nativescript-videoplayer" loaded="pageLoaded">
...
Should I change the path to xmlns:Video to something else than above inside Demo-app?

**Comment by bradmartin** [comment]
if you aren't modifying the demo then it should work, let me do a test run of it

**Comment by bradmartin** [comment]
oh I think I know, it's likely not transpiling the TS. I manually do that just by habit. I bet that's the issue so if you went and looked in your node_modules you won't see any .js files - shouldn't even have the .ts source files.

**Comment by guru1966** [comment]
I can only see .ts source files inside node_modules/nativescript-videoplayer/. Seems not compiled to .js source files. You maybe right regarding this. How to resolve that? 

![skarmavbild 2016-09-29 kl 21 06 53](https://cloud.githubusercontent.com/assets/4431497/18968307/c200bdce-8688-11e6-959e-0779d735a7fe.png)

**Comment by bradmartin** [comment]
run `tsc` in your terminal - when at the plugin source. So path to `nativescript-videoplayer` (the root of the cloned repo and run `tsc` you'll see it process and then you'll have .js files in the root for the plugin, then path to the demo project. Last `run` or `livesync` should prepare the plugin which should update the source in the node_modules for the videoplayer and then it will work.

**Comment by guru1966** [comment]
Yes, running tsc and creating .js files inside nativescript-videoplayer resolved it ! Thank you !

**Comment by bradmartin** [comment]
Yea - I need to add the scripts to the package.json and doc it on the readme. Might do that later 👍

**Comment by bradmartin** [comment]
Copied some scripts over from another project, should fix the issue going forward to not skip the transpile step - didn't test though.
