### ISSUE TITLE
Can not change video-source to play other Video-file

### ISSUE THREAD

**Issue by guru1966** [bradmartin/nativescript-videoplayer#40]
Hello !
I am trying to deploy my code to Android. This works fine on Iphone but not on Android.
I have in my xml, the following:
      <VideoPlayer:Video id="nativeVideoPlayer" width="100%" height="90%"    
                             verticalAlignment="middle"
                               src=" {{ urlsrc }} "
                               loaded="{{ videoplayerLoaded }}"
                               finished="{{ videoFinished }}"
                               autoplay="true"
                               left="0" top="40"
     />

I am trying to change the src property of the Video in my Typescript.code as follows:

 this._videoPlayer.src = 'https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4';
 this.playVideo();

I have even tested with the following without result:
this.set("urlsrc", 'https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4');
or 
this.src = 'https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4';

Still same problem, I can not change the video-source or replace it with another video-force. I can only play first video-file and can not change and play other video-files. As stated I do not have any such problem in Iphone to change Video-source using this.set("urls",...).

When I compile it via tsc, I get the following complain:
error TS2339: Property 'src' does not exist on type 'Video'.

Any idea why I have this problem ?

**Comment by bradmartin** [comment]
Possibly the typo here: https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer.android.ts#L131 should be `this._android`

you can ignore the TS warning for now.

**Comment by bradmartin** [comment]
Published with the typo fix, although don't think that's the real issue but worth a shot before debugging it.

**Comment by guru1966** [comment]
Same problem, did not affect the change of Video source with for example  this.set("urlsrc", 'https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4');
Works only once inside 
constructor(mainpage: Page) {
        super();
        ....
       this.set("urlsrc", 'https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4');
}
But in other places using same method this.set("urlsrc", '...') to change the video source urlsrc does not have any affects and only same video src is keep replaying.

**Comment by bradmartin** [comment]
can you provide a sample project so I can find the issue faster?

**Comment by matart15** [comment]
I don't know it is related but I have something similar 
https://github.com/bradmartin/nativescript-videoplayer/issues/43

**Comment by vilius365** [comment]
Did anyone get to the bottom of this? Its still not possible to change the src after it was initialized in the constructor. Should it be able to change the video source and play different video?

**Comment by matar15** [comment]
for now I am doing like this. works on android. 
https://github.com/bradmartin/nativescript-videoplayer/issues/43#issuecomment-255110185

Did not look into ios code but i think similar can be done.

**Comment by guru1966** [comment]
Hello !
My laptop crashed so why I could not answer it before now ...
Still have same problem. 

I have pushed my sample code on the following link.
[https://github.com/guru1966/SampleNativeScriptVideoPlayer](url)

As you can see setting videosrc has no effect to play new video file.
this.set("videosrc",src);

Any idea how to resolve it ?

**Comment by lukeramsden** [comment]
@bradmartin have you found a solution to this yet?

**Comment by guru1966** [comment]
Unfortunately not :(

**Comment by bradmartin** [comment]
Sorry, I've not had time to look into it. This line is important to change the source of the player https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer-common.ts#L24 as well as the onSourceChange in the distinct platform files for android/ios. Something must be off in those bits of the source if you want to take a look. I'll try to find some time for this plugin in the coming weeks but really busy this month before the holidays 😞

**Comment by bradmartin** [comment]
Just confirmed this works. I'm adding a button to the demo project that changes the video player's `src`.
