### ISSUE TITLE
Video Not Loading in Angular 2 and Nativescript

### ISSUE THREAD

**Issue by joshapgar** [bradmartin/nativescript-videoplayer#42]
I have added the code to my template, but it is not showing in the app.  Do you have to reference the code in the template differently in an Angular 2 and Nativescript application?

Template Code:
```
<StackLayout>
    <Label text="Grand Hall"></Label>
    <VideoPlayer:Video #nativeVideoPlayer controls="true" autoplay="true" height="280" src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" />
</StackLayout>
```

Component Code:
```
import { Component, ElementRef, ViewChild } from "@angular/core";
import { Video } from 'nativescript-videoplayer';


@Component({
	selector: "grandhall",
	templateUrl: "pages/grandhall/grandhall.html",
	styleUrls: ["pages/grandhall/grandhall-common.css", "pages/grandhall/grandhall.css"]
})

export class GrandHallComponent {
	@ViewChild("nativeVideoPlayer") nativeVideoPlayer: ElementRef;
}	
```

**Comment by bradmartin** [comment]
I think I answered your question on SO not long after you posted. The NS slack channel has a bot that links SO questions so I saw it not long after it posted. 

`registerElement` is what you're missing. I've also added this to the README.

**Comment by joshapgar** [comment]
For anyone else who comes across this, or you may want to add it to the read me.

Put this at the top of the component or where the app is bootstrapped:

```
import { registerElement } from "nativescript-angular/element-registry";
registerElement("VideoPlayer", () => require("nativescript-videoplayer").Video);
```

Then adjust your template code to:

```
<VideoPlayer
	  src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
	  autoplay="true" 
	  height="300"></VideoPlayer>
```

Thanks again and nice work on the plugin.

**Comment by matart15** [comment]
If i understood right this code is for typescript right
```
<VideoPlayer
      src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
      autoplay="true" 
      height="300"></VideoPlayer>
```
I too  spent 20+ minute on this one in first implementation.

We should point this out in readme.

**Comment by bradmartin** [comment]
That snippet isn't for typescript. That's the xml and with angular2 you
have to explicitly close all components. Which you have in that snippet.
The import statement though is ts code to call register element and I added
that to readme yesterday. I'll add the xml snippet for angular also so it's
copy paste for others

**Comment by bradmartin** [comment]
Added the template code to the README.
