### ISSUE TITLE
VideoPlayer with ScrollView

### ISSUE THREAD

**Issue by HoangJK** [bradmartin/nativescript-videoplayer#44]
Hello,

I use nativescript-videoplayer in ScrollView. When I scroll up or scroll down, video frame have a problem, it have black frame in bottom of video.
![screen shot 2016-11-03 at 3 51 53 pm](https://cloud.githubusercontent.com/assets/12653469/19960156/97c1bbf6-a1dd-11e6-801b-99b1b0fb2848.png)

Thanks.

**Comment by bradmartin** [comment]
Can you provide your ui markup? Thanks

**Comment by HoangJK** [comment]
This is my UI markup:
<ScrollView #scrollView backgroundColor="#ddd"  padding="10 5 0 5">
    <StackLayout orientation="vertical">
        <VideoPlayer
        marginBottom="10"
        src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
        autoplay="true" 
        controls="true"
        height="300"></VideoPlayer>
        <VideoPlayer
        marginBottom="10"
        src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
        autoplay="true" 
        controls="true"
        height="300"></VideoPlayer>
        <VideoPlayer
        marginBottom="10"
        src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
        autoplay="true" 
        controls="true"
        height="300"></VideoPlayer>
        <VideoPlayer
        marginBottom="10"
        src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
        autoplay="true" 
        controls="true"
        height="300"></VideoPlayer>
        <VideoPlayer
        marginBottom="10"
        src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
        autoplay="true" 
        controls="true"
        height="300"></VideoPlayer>
        <VideoPlayer
        marginBottom="10"
        src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
        autoplay="true" 
        controls="true"
        height="300"></VideoPlayer>
        <VideoPlayer
        marginBottom="10"
        src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
        autoplay="true" 
        controls="true"
        height="300"></VideoPlayer>
    </StackLayout>
</ScrollView>

Please see that video demo: https://goo.gl/photos/oAnefkMs27AB8jKt8

Thanks.

**Comment by bradmartin** [comment]
Without testing I'm guessing it's margin bottom that's causing it. You
could try adjusting the layout by adding padding to the parent of the
player or to the player itself and see what happens.

**Comment by bnussey** [comment]
Hey @HoangJK was this on Android or iOS? Or both?

**Comment by bradmartin** [comment]
Not visible on android 6.0 or 5.1 from my demo test. I'm closing this for now. I'd also avoid using the markup provided in a production app. You would likely not want to load that many video players at once with remote files. You'll have heavy network use for the video files. The better option is to use a list view with a couple of instances of a video player being used. Turning off autoplay so there isn't work being done when not needed and also hooking into the `loaded` event of the video player and checking the instance's `src` to make sure it is the correct video instance you want to play for the item in the listview `items` data set.
