### ISSUE TITLE
"finished" is not working under Angular2

### ISSUE THREAD

**Issue by emanahov** [bradmartin/nativescript-videoplayer#45]
Following your specific guidelines for Angular in Readme the video is playing but when finished the function specified in the "finished" property is not fired. What could be the problem?

This is my app.component.html

<VideoPlayer
                src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
                autoplay="true" 
                controls="true"
                finished="{{onFinished}}"
                height="300">
            </VideoPlayer>

This is my app.component.ts

import { Component } from "@angular/core";
import {registerElement} from "nativescript-angular/element-registry";
registerElement("VideoPlayer", () => require("nativescript-videoplayer").Video);

@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
  

   
    public onFinished() {
        console.log ('Video finished playing.')
    }
}

Please, help.

**Comment by bnussey** [comment]
Do you have the finished callback defined in the template? Should be (finished)="onFinished()"

**Comment by emanahov** [comment]
With this syntax it works - I did not enclosed the finished in parenthesis.

Thanks,
Please, close it.
