### ISSUE TITLE
Video iOS run in background

### ISSUE THREAD

**Issue by HoangJK** [bradmartin/nativescript-videoplayer#46]
Hello,

I have a question about your plugin. In iOS, I use video player in ListView, when I scroll ListView to other item, ListView auto remove video player, and when I scroll in it again ListView generate new video player. And the old video player still play in background. How to turn off video player run in background when scroll to other item in ListView?

Thanks.

**Comment by bnussey** [comment]
Not sure of your exact implementation but I would suggest using the destroy method

**Comment by manijak** [comment]
I've seen similar issue when navigating away from the page that contains the video. The video/audio continues to play in background.

**Comment by lukeramsden** [comment]
@manijak I just noticed this too, but after some testing it turns out it only happens on iOS.

**Comment by lukeramsden** [comment]
@bradmartin Is it because Android kills the view when you leave but iOS doesn't?

**Comment by lukeramsden** [comment]
@manijak @bradmartin Moved video playing on page leave to #50
