### ISSUE TITLE
Video.destroy() doesn't work

### ISSUE THREAD

**Issue by lukeramsden** [bradmartin/nativescript-videoplayer#47]
Okay, so I have this code
```
var old_video = page.getViewById("video");
if(old_video !== undefined) {
    old_video.destroy();
}
```

But when I run it, the video freezes and the controls stop working, but the video won't disappear. BUT! If I run the code a second time, it says `Cannot read property 'stopPlayback' of null'`. So why is the video not disappearing? Is there something I'm doing wrong??

**Comment by lukeramsden** [comment]
woops

**Comment by bradmartin** [comment]
Been a while since I've worked on this but from memory `.destroy()` is a method to mainly free resources on the device. It won't remove from the view so you'll need to actually handle that yourself to remove the view from the layout. Hope that helps. I don't think we should add that as part of the plugin either so I don't anticipate that changing at this time 😄 let me know if that makes sense or not.

**Comment by lukeramsden** [comment]
@bradmartin would view.removeChild() work?

**Comment by bradmartin** [comment]
Something like that 😄 if `view` is the layout with the child possibly. Sorry, in a meeting right now 😢 

https://docs.nativescript.org/api-reference/classes/_ui_layouts_layout_.layout.html#removechild

**Comment by lukeramsden** [comment]
@bradmartin Alright thanks 👍 💯 :)

**Comment by princy05** [comment]
> 
> 
> Something like that smile if `view` is the layout with the child possibly. Sorry, in a meeting right now cry
> 
> https://docs.nativescript.org/api-reference/classes/_ui_layouts_layout_.layout.html#removechild

Hello Brad,
I used removeChild along with video.destroy, it is removing the view correctly for ios but for android the destroy method is not removing the child properly. Could you please help me with this?

**Comment by lukeramsden** [comment]
@princy05 this is the code I use to destroy the player:

```
  public destructor() {
    let container = this.page_.getViewById(
      'video-player-container',
    ) as StackLayout;

    let player: Video;

    if (container) player = container.getViewById('video-player') as Video;

    if (player) {
      console.log('player.destroy');
      player.destroy();
      container.removeChild(player);
    }
  }
```
