### ISSUE TITLE
[iOS] Cannot change `controls` property after init

### ISSUE THREAD

**Issue by manijak** [bradmartin/nativescript-videoplayer#49]
I have this famous iOS issue 'Unable to simultaneously satisfy constraints' when using the VideoPlayer. I know this is a bug in the AVPlayer, but I cannot seem to get around it. 

The way around it is to disable the `showsPlaybackControls` before attaching the video-source. Then enable it. I can see that you have implemented this in the plugin-code for ios. But the error is still present. 

I get the video-source url from a service, so I change the `controls` property to `true` after the binding is set. But even then the controls are not shown, which tells med that perhaps `controls` property cannot be set after init?

I have also tried setting `controls="true"` in the xml, but then the above error appears when going fullscreen video.

**Comment by bnussey** [comment]
Hey @manijak I was experiencing this issue myself and solved it as you said we have. 

Are you running ng2?

**Comment by manijak** [comment]
I'm using vanilla {N}. Hmmm I see now that I have version 1.1.5 of the plugin (for some reason). Have no idea why it installed such a low version. Will try with 2.0.0.

**Comment by manijak** [comment]
Ok, tested with 2.0.0. Still the same, this happens when I press the Fullscreen icon, then it pours out the mentioned errors.

**Comment by manijak** [comment]
I am not seeing this issue anymore. Could be due to the recent updates, thanks.
