### ISSUE TITLE
[iOS] Video continues playing after you leave page

### ISSUE THREAD

**Issue by lukeramsden** [bradmartin/nativescript-videoplayer#50]
Started at #46 

If you leave a page, the video continues playing in the background, but only on iOS. Potential fix to make video run destroy() or suspend() on leaving the page?

**Comment by bnussey** [comment]
I believe this is easily solved by just running the destroy method on the video. Videos must be destroyed as on iOS there is a hard limit of around 15-20 videos. Soon as you hit this, it'll stop rendering videos.

**Comment by lukeramsden** [comment]
@bnussey yes, but maybe it should be done automatically by the plugin? That would make everything simpler.

**Comment by bnussey** [comment]
Hey @lukeramsden I disagree, its a common pattern and good practice to run necessary destroys when leaving a page.

**Comment by manijak** [comment]
Did not know about `destroy()`, that will do :)

**Comment by lukeramsden** [comment]
I knew about it, that's what I'm currently doing, I just think it's good practice to have to plugin clean up after itself.

**Comment by bnussey** [comment]
@lukeramsden -- the plugin will not know when to do that, it relies on you to specify that. Feel free to provide a PR if you'd like though.

**Comment by lukeramsden** [comment]
Is there no way to bind it to the onNavigatingFrom event? I'll have a go at it later cause I'm on my phone right now.

**Comment by manijak** [comment]
@bnussey  Just FYI, I tested it with `destroy()` and it works. But when you return back to the video-page, the binding is not being set. 

```
Binding: Binding error while setting property src of Video<mainVideoPlayer>@file:///app/views/home/partial-video.xml:12:17;: TypeError: null is not an object (evaluating 'this._playerController.player = this._player')
```

**Comment by bnussey** [comment]
Hey @manijak just depends on your specific scenario. If you want to come back to the video and play it, then you just need to pause it. If you never want to come back to the video, and the page is going to be reloaded, you destroy it.

**Comment by pandasoft0** [comment]
Here is another issue. The video player gets paused and mute when I switch to the iOS home screen, but when I lock device everything works correctly. I think the issue is in the native script’s videoplayer.
