### ISSUE TITLE
[Android] Cannot see controls

### ISSUE THREAD

**Issue by manijak** [bradmartin/nativescript-videoplayer#52]
Updated to the latest version the other day, testing on Android, I am not seeing any player controls (controls is set to true in xml).

**Comment by manijak** [comment]
Any update on this? Seems like the `onTouch` event never fires.
```
this._android.setOnTouchListener(new android.view.View.OnTouchListener({
            get owner(): Video {
                return that.get();
            },
            onTouch: function (/* view, event */) {
                this.owner.toggleMediaControllerVisibility();
                return false;
            }
        }));
```

**Comment by bradmartin** [comment]
Haven't touched this in a while @manijak - I'm finding some more time here in the coming weeks so I'll circle back and fix issues on some plugins soon.

**Comment by markhatchell** [comment]
I am having an issue with the controls not showing also. Will fork and attempt to debug and fix.

**Comment by markhatchell** [comment]
Looks like the controls show properly when the video player is just in a stack layout. A complex hierarchy seems to make the controls not appear. Still testing on what exactly makes them disappear.

**Comment by markhatchell** [comment]
It appears that when the video player is in a modal the controls don't show. They might be behind the modal in the view stack?

**Comment by bradmartin** [comment]
Sounds like a layering issue. Testing this on Android I'm assuming?

**Comment by markhatchell** [comment]
Yep on android.

**Comment by markhatchell** [comment]
possibly adding a bringToFront() call on the player controls will fix it.

**Comment by bradmartin** [comment]
Okay, so yea likely a layering issue. Those are a pain to deal with, had some in the past on this plugin I think.

**Comment by bradmartin** [comment]
Yea at one time I think we even messed with the zIndex settings or something but it was temporary fix.

**Comment by markhatchell** [comment]
ill test it out

**Comment by markhatchell** [comment]
so `this.mediaController.bringToFront();` did not seem to do it.

**Comment by markhatchell** [comment]
I was also curious why a native MediaPlayer was not used?

**Comment by bradmartin** [comment]
Check some of the history on the android source and you'll find some layer stuff we worked around long time ago. Might help some

**Comment by markhatchell** [comment]
will do

**Comment by markhatchell** [comment]
Sorry, disregard the MediaPlayer question. I just saw the TextureView at first.

**Comment by markhatchell** [comment]
So for sure the controls are there behind the modal, that is confirmed when the opacity of the modal page is set to 0.

**Comment by bnussey** [comment]
Hey @markhatchell if you're on NS slack community you can hit me up with any questions and I can assist

**Comment by bnussey** [comment]
We dont use the default controls on our project so we never tested that after switching to textureView

**Comment by markhatchell** [comment]
@bnussey Hey, I am not yet on the community, certainly want to join though!

**Comment by markhatchell** [comment]
@bnussey I can not seem to find the slack channel could you send me an invite please.

**Comment by bnussey** [comment]
http://developer.telerik.com/wp-login.php?action=slack-invitation

**Comment by manijak** [comment]
hmmm... I'm not using the videoplayer in a modal, just a bunch of layouts. The parent container is a cardview. The controls show the first time and after a few seconds they hide. Tapping on the videoplayer does nothing. So I can't pause/stop the video once it starts :)

Should say that initially my videoplayer is without a source. So when the view is loaded, there is no url set. It is set when the user is ready to play the video. This is on android, ios works like a charm. 

PS. As I understand there is no fullscreen feature in the player?

**Comment by bradmartin** [comment]
Yea no full screen out of the box ☹️

**Comment by bradmartin** [comment]
The controls are visible for me in the demo app on Android 5.1, 6.0 and 4.4. 

@manijak care to share your layout, might help uncover what's happening.

**Comment by manijak** [comment]
I found out why that was happening in my app. I had a layout over the videoplayer, like a overlay, with image and play button. When the user taps it, it animates to 0 opacity and starts the video. 
So when the user taps the video player, nothing happens. Had to add `visibility=collapsed` on the overlay, for the player controls to show up... This was not the case on iOS, therefore the confusion :)
