### ISSUE TITLE
Issue with install, '0' of undefined

### ISSUE THREAD

**Issue by SamuelGRwebfab** [bradmartin/nativescript-videoplayer#54]
Hello brad,

I was just attempting to install this plugin (using `tns plugin add nativescript-videoplayer`). I was given this error on install `Cannot read property '0' of undefined`
I also was given this yellow warning even tho i have zone isntalled (idk if this is related or not) `The package zone.js@0.7.6 does not satisfy its siblings' peerDependencies requir
ements!
`
Any ideas on how to fix this?

Thanks!

**Comment by bradmartin** [comment]
Never seen that :/ yellow warnings in terminal during package installs are
usually not a major issue but of course can be. Try checking your outdated
deps and updating them and see if the problem goes away.

**Comment by SamuelGRwebfab** [comment]
@bradmartin after updating all of my @angular modules to 2.4.5, my rxjs to 5.0.1 and lowering my zone.js to 0.7.2, it worked. Thanks! (hope this helps someone in the future)

thanks Brad!
