### ISSUE TITLE
source with http are not working. Only https links works

### ISSUE THREAD

**Issue by adnanakbar** [bradmartin/nativescript-videoplayer#61]
Its hard to find https sample sources. Anyway I have tried several http links that do not work.

sample link https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 works, but if you change it to http it won't work even though its still a valid link.

http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

Thanks,
Adnan

**Comment by bradmartin** [comment]
What platform? If on iOS you need to set a key in your plist file to allow
the URL to work. If android it should be okay, I'll test later this weekend.
