### ISSUE TITLE
Possibility to destroy video on leaving page

### ISSUE THREAD

**Issue by b4rtt** [bradmartin/nativescript-videoplayer#65]
Hi,

I am trying to destroy video everytime when I leave page where it's playing but it doesn't work.
Is any recommended way how to do it with this pack?

Cound someone post me a piece of code how to destroy video?

Thank you so much

**Comment by bradmartin** [comment]
Can you paste your code that you have trying to do this? The `destroy()` method should be sufficient. So let's figure out what's happening 😄

**Comment by b4rtt** [comment]
`import {Component} from "@angular/core";
import {Location} from "@angular/common";
import {Page} from "../page";
import {ActivatedRoute} from '@angular/router';

import{ArticlesService} from '../../services/articles.service';
import * as SocialShare from "nativescript-social-share";
import {RouterExtensions} from "nativescript-angular/router";

import {Video} from "nativescript-videoplayer";


@Component({
    selector: 'article-page',
    templateUrl: 'pages/article/article.page.html',
    styleUrls:  ['pages/article/article.page.css'],
    providers: [ArticlesService]
})
export class ArticlePage extends Page {
    

    constructor(private location: Location, private route:ActivatedRoute, private articlesService: ArticlesService, private routerExtensions: RouterExtensions) {
        super(location);

    }

    videoTap(vPlayer: Video) {
        vPlayer.destroy();
     }
    
}`

`   <VideoPlayer #vPlayer
                src="{{articleVideo}}"
                autoplay="false" 
                controls="true"
                width="100%"
                height="210"
               ></VideoPlayer>`

This is way how to I trying this.
But maybe it will be better do it some way how to turn off video everytime when I leave video page.

I have app where I can open article. Some articles has video. I play video. Go back and sound is still playing even when I play video from another article.

Thank u for help

**Comment by bradmartin** [comment]
I dont know the NS+NG too well. So in your `videoTap` function where is that defined and are you sure the argument `vPlayer` is an instance of the `VideoPlayer`? In plain NS a tap event passes an object of type `EventData` which you can then get an instance of the control via the `.object` property. 

If you are receiving `no method on undefined` or something similar then you likely don't have an instance of the `VideoPlayer` so you'd need to make sure you get an instance and then call the `destroy` method on the player. 

@bnussey - don't you use Angular? Can you see what's wrong with the snippet above? My assumption is ^^^ and that the tap event isn't setup correctly to be executed. I would also guess you can get the VideoPlayer instance with a global method of `getViewById()` or something similar with NG. Thanks

**Comment by ls-spavel** [comment]
@bradmartin You are correct about the tap event in NNG. 

The method I use to get a ui component like this is to use Angular's [ViewChild](https://angular.io/docs/ts/latest/api/core/index/ViewChild-decorator.html).

In this case you would need to import ViewChild from `@angular/core` and then add the ViewChild to the class
```
export class ArticlePage extends Page {
    @ViewChild(Video) public vPlayer: Video;

    constructor(private location: Location, private route:ActivatedRoute, private articlesService: 
    ArticlesService, private routerExtensions: RouterExtensions) {
        super(location);
    }

    videoTap(vPlayer: Video) {
        this.vPlayer.destroy();
    }
}
```

**Comment by bnussey** [comment]
I use Angular and do it like so:
```
@ViewChild("videoPlayer") _videoPlayer: ElementRef;
```
Then you can access the destroy method by doing this:
```
this._videoPlayer.nativeElement.destroy();
```

**Comment by bnussey** [comment]
Didn't see @ls-spavel he has summed it up perfectly, thank you for that. Closing this issue for now.

**Comment by b4rtt** [comment]
@ls-spavel @bnussey thank you so much for your help. I dunno why but my app still crashes.

`[aqme] 254: AQDefaultDevice (1): skipping input stream 0 0 0x0
[aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
[aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
[aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
Apr 11 09:29:45 --- last message repeated 4 times ---
1   0x10f8927cb NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x10ff671ee ffi_closure_unix64_inner
3   0x10ff67b22 ffi_closure_unix64
4   0x110c682f4 -[UIControl sendAction:to:forEvent:]
5   0x110c6860f -[UIControl _sendActionsForEvents:withEvent:]
6   0x110c6754a -[UIControl touchesEnded:withEvent:]
7   0x11100c35d _UIGestureEnvironmentSortAndSendDelayedTouches
8   0x111007374 _UIGestureEnvironmentUpdate
9   0x111006da7 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:]
10  0x111005f6e -[UIGestureEnvironment _updateGesturesForEvent:window:]
11  0x110b5307a -[UIWindow sendEvent:]
12  0x110affc90 -[UIApplication sendEvent:]
13  0x1112e1f5c __dispatchPreprocessedEventFromEventQueue
14  0x1112d9eba __handleEventQueue
15  0x1135dec01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
16  0x1135c40cf __CFRunLoopDoSources0
17  0x1135c35ff __CFRunLoopRun
18  0x1135c3016 CFRunLoopRunSpecific
19  0x115568a24 GSEventRunModal
20  0x110ae25b4 UIApplicationMain
21  0x10ff6797d ffi_call_unix64
22  0x11f3036b0
file:///app/pages/article/article.page.js:64:21: JS ERROR TypeError: undefined is not an object (evaluating 'this.vPlayer.destroy')
Apr 11 09:29:45 Roman-MacBook-Air com.apple.CoreSimulator.SimDevice.AB4B81E5-D9EF-40EB-B3D9-CDACC149964A.launchd_sim[39526] (UIKitApplication:org.romansimr.HelloWorld[0xebd3][39551][40046]): Service exited due to Segmentation fault: 11`


my code looks like this
`  <VideoPlayer #vPlayer
                src="{{articleVideo}}"
                autoplay="false" 
                controls="true"
                width="100%"
                height="210"></VideoPlayer>`

---

`import {Component, ViewChild, ElementRef} from "@angular/core";
import {Location} from "@angular/common";
import {Page} from "../page";
import {ActivatedRoute} from '@angular/router';

import{ArticlesService} from '../../services/articles.service';

import * as SocialShare from "nativescript-social-share";

import {RouterExtensions} from "nativescript-angular/router";

import {Video} from "nativescript-videoplayer";


@Component({
    selector: 'article-page',
    templateUrl: 'pages/article/article.page.html',
    styleUrls:  ['pages/article/article.page.css'],
    providers: [ArticlesService]
})

export class ArticlePage extends Page {


    @ViewChild(Video) public vPlayer: Video;

    constructor(private location: Location, private route:ActivatedRoute, private articlesService: ArticlesService, private routerExtensions: RouterExtensions) {
        super(location);
    }

    videoTap(vPlayer: Video) {
        this.vPlayer.destroy();
    }
}

interface Article{
    id:string;
    article_heading:string;
    article_text:string;
    article_photo:string;
    article_perex:string;
    article_author:string;
    strip_id:string;

}`

**Comment by bnussey** [comment]
You wanna try and do it like mine? Also for multiple lines of code you can do ```, makes it a lot easier to read.

**Comment by b4rtt** [comment]
Your way give me this error. I am kinda frustrated :( I tried almost everything.

``
[aqme] 254: AQDefaultDevice (1): skipping input stream 0 0 0x0
[aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
1   0x10263b7cb NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x102d101ee ffi_closure_unix64_inner
3   0x102d10b22 ffi_closure_unix64
4   0x103a112f4 -[UIControl sendAction:to:forEvent:]
5   0x103a1160f -[UIControl _sendActionsForEvents:withEvent:]
6   0x103a1054a -[UIControl touchesEnded:withEvent:]
7   0x103db535d _UIGestureEnvironmentSortAndSendDelayedTouches
8   0x103db0374 _UIGestureEnvironmentUpdate
9   0x103dafda7 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:]
10  0x103daef6e -[UIGestureEnvironment _updateGesturesForEvent:window:]
11  0x1038fc07a -[UIWindow sendEvent:]
12  0x1038a8c90 -[UIApplication sendEvent:]
13  0x10408af5c __dispatchPreprocessedEventFromEventQueue
14  0x104082eba __handleEventQueue
15  0x106387c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
16  0x10636d0cf __CFRunLoopDoSources0
17  0x10636c5ff __CFRunLoopRun
18  0x10636c016 CFRunLoopRunSpecific
19  0x108281a24 GSEventRunModal
20  0x10388b5b4 UIApplicationMain
21  0x102d1097d ffi_call_unix64
22  0x11211e6b0
file:///app/pages/article/article.page.js:63:26: JS ERROR TypeError: undefined is not an object (evaluating 'this._videoPlayer.nativeElement')
Apr 11 20:24:16 Roman-MacBook-Air com.apple.CoreSimulator.SimDevice.AB4B81E5-D9EF-40EB-B3D9-CDACC149964A.launchd_sim[42346] (UIKitApplication:org.romansimr.HelloWorld[0x4d44][42371][42589]): Service exited due to Segmentation fault: 11
``

**Comment by bradmartin** [comment]
This is the issue:
```
file:///app/pages/article/article.page.js:63:26: JS ERROR TypeError: undefined is not an object (evaluating 'this._videoPlayer.nativeElement') 
```

We need to figure out what your instance of `this._videoPlayer` is undefined when you execute that and you should be good to go.

**Comment by b4rtt** [comment]
Oh my mistake! It's working! Thank you so much. I really appreciate it. :) 👍

**Comment by NL33** [comment]
In case others come across this, here is the relevant code that I found was required for the destroy method to work in Angular (and iOS):

html:
` <VideoPlayer #videoPlayer src="{{videoSource}}" autoplay="false" height="300"></VideoPlayer>`

ts:
```
import { Component, OnInit, ViewChild, ElementRef } from "@angular/core";
import { Page } from "tns-core-modules/ui/page";

import { Video } from 'nativescript-videoplayer';
registerElement("videoPlayer", () => Video);
...
export class CoolComponent implements OnInit {
   @ViewChild("videoPlayer") _videoPlayer: ElementRef;
  ...

    ngOnInit(): void {
        this.page.on('navigatingFrom', (data) => {  //could also have this code in a separate function called on tap
            this._videoPlayer.nativeElement.destroy();
        })
    }
```
Note that destroying the element may cause problems if you navigate to the page via the back button (it won't re-register the element, I believe, but the element will have been destroyed).

For this reason, on the pages where I call destroy I remove the back button from any subsequent pages that are navigated to from that page (remove with:  `<NavigationButton visibility="collapsed"></NavigationButton>`)

 I am still struggling with the fact that on slower devices (like older ipads, for example), the video player fails to load entirely. But that is another [issue](#134 ).
