### ISSUE TITLE
No sound while mute/silent switch is engaged on iOS

### ISSUE THREAD

**Issue by andrewkluck** [bradmartin/nativescript-videoplayer#66]
@bradmartin thank you for this great plugin!  We are having a minor issue with video sound not playing when the mute/silent switch is engaged on iPhone 5, 6, and 7.  While this makes sense (you would expect the mute switch to mute all audio) other apps do not respond this way causing users to suspect something is wrong with our app when they try to watch a video and do not realize their mute switch is on.

We believe this issue is might be related to background audio capabilities and would like to attempt to set the session category for AV Player by doing something like AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback) but we are uncertain as to the implementation.  It seems that in your plugin you are simply allowing the system to handle the  audio session category rather than setting it explicitly.

Any guidance you could offer would be greatly appreciated!

Links to a similar conversations for reference: 
http://stackoverflow.com/questions/3740528/play-sound-on-iphone-even-in-silent-mode
http://stackoverflow.com/questions/30280519/how-to-play-audio-in-background-swift

**Comment by bradmartin** [comment]
I won't claim to be an iOS expert by any means 😄 it is my kryptonite sometimes.

I believe this is what you might be looking for: https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/ConfiguringAudioSettings/ConfiguringAudioSettings.html

**Comment by bnussey** [comment]
Thanks for submitting this @andrewkluck as its a great point. However you will find most apps don't play sound when muted immediately. Snapchat doesn't, and I believe Facebook has the video muted while playing in the feed. We could look at introducing this as a configurable option. If you are up for it, I'd welcome a PR for this.

**Comment by andrewkluck** [comment]
@bradmartin and @bnussey thanks for your response and examples, I think it will help a lot. Have a few projects going right now but am planning to get back to this soon.  I'll let you know what I come up with and If I feel like I have something worthy of adding I'll submit a PR.  Thanks again!

**Comment by andrewkluck** [comment]
@bradmartin, @bnussey - I have a working solution.  This has been tested successfully on iPhone 7 with audio playing while mute/silent switch is engaged.  

**This code is executed in the app.js file** as @bradmartin suggested. I am using the nativescript-platform plugin from NathanaelA at https://github.com/nathanaela/nativescript-platform.

```
require("./bundle-config");
require('nativescript-platform');

"use strict";
var application = require("application");

if(nsPlatform.ios){
	
	var MyDelegate = (function (_super) {
	    __extends(MyDelegate, _super);
	    function MyDelegate() {
	        _super.apply(this, arguments);
	    }
	    MyDelegate.prototype.applicationDidFinishLaunchingWithOptions = function (application, launchOptions) {

	    	var audioSession = AVAudioSession.sharedInstance();

		    try {
		        audioSession.setCategoryError(AVAudioSessionCategoryPlayback);

		        audioSession.setActiveError(true);
				console.log("audioSession category set and active");

		    } catch(err) {
		        console.log("setting audioSession category failed");
		    }

	        console.log("applicationWillFinishLaunchingWithOptions: " + launchOptions);
	        return true;
	    };
	    MyDelegate.prototype.applicationDidBecomeActive = function (application) {
	        console.log("applicationDidBecomeActive: " + application);
	    };
	    MyDelegate.ObjCProtocols = [UIApplicationDelegate];
	    return MyDelegate;
	})(UIResponder);
	application.ios.delegate = MyDelegate;
}

application.start({ moduleName: "main-page" });
```

Also, if you want you audio to play in background mode (while the phone is locked, etc...) please **add the following to your info.plist file**:

```
<key>UIBackgroundModes</key>
<array>
	<string>audio</string>
</array>
```

Along with the two links in @bradmartin's comment above, I also used the following references: 
- https://docs.nativescript.org/core-concepts/application-lifecycle#ios-uiapplicationdelegate
- https://developer.apple.com/library/content/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionCategoriesandModes/AudioSessionCategoriesandModes.html#//apple_ref/doc/uid/TP40007875-CH10

**Comment by andrewkluck** [comment]
I have confirmed that the above solution solves the no sound while mute/silent switch is engaged on iOS issue on iPhone 5, 6, and 7 (actual hardware).

**Comment by divyesh008** [comment]
@andrewkluck  It's not working in iPhone 6 when with video.

I have set below code in AppDelegate's finished launching method
    ```
NSError nsErr;
                AVAudioSession instance = AVAudioSession.SharedInstance();
                instance.SetCategory(new NSString("AVAudioSessionCategoryPlayback"), AVAudioSessionCategoryOptions.MixWithOthers, out nsErr);
                instance.SetMode(new NSString("AVAudioSessionModeDefault"), out nsErr);
                instance.SetActive(true, AVAudioSessionSetActiveOptions.NotifyOthersOnDeactivation, out nsErr);
```

Player code from my .net standard project:
 var MyViewModelContext = ((DetailViewModel)this.BindingContext);
            
            videoPlayer.AutoPlay = true;
            videoPlayer.Source = MyViewModelContext.Source;
            videoPlayer.Play();
