### ISSUE TITLE
Request: Videoplayer in Nativescript 3.0 for Breaking Changes

### ISSUE THREAD

**Issue by KuboStraka** [bradmartin/nativescript-videoplayer#68]
Hi,
I just upgraded my project to {N} version 3.0.

Since then, It is no longer possible to use your Videoplayer plugin. I am using NativeScript Angular so I registered Video element as you wrote and when I want to run video inside app this error occurs:
`Failed to find module: "ui/core/proxy", relative to: app/tns_modules/`

I assume it is because of this:

> Bindable(“ui/core/bindable” module), ProxyObject (“ui/core/proxy” module) and DependencyObservable ("ui/core/dependency-observable" module) are removed.
Consider using View, ViewBase or Observable instead.

as is wrote in: [https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md](url)

Can you please help me resolve this issue?

P.S.: before {N} version 3.0 everything worked fine

**Comment by bradmartin** [comment]
Hi @KuboStraka - this plugin has not been updated for NS 3+. I'll accept a PR that handles the breaking changes and provides the updates if you want. So for now this plugin will not work on 3+ until it's updated.

Let me know if you're interested in contributing for this.

Thanks

**Comment by bnussey** [comment]
Once 3.0 is officially released we'll do some work to make it compatible.

**Comment by bnussey** [comment]
Hi @KuboStraka this has now been updated to 3.0 .. please test and advise if any issues, thank you.

**Comment by KuboStraka** [comment]
Hi @bnussey that's great news :). I will test it and let you know.
Thanks again guys for all that great work .
