### ISSUE TITLE
Android and iOS different behavior

### ISSUE THREAD

**Issue by b4rtt** [bradmartin/nativescript-videoplayer#69]
Hi,

I have little problem. When I leave page (back button) with playing video on iOS - video is still playing. But on android it stops. Is there some easy solution?

Thank you

**Comment by bradmartin** [comment]
Simple solution would be to hook into one of the page navigation events and destroy the video player (or stop the playing video). Let me know if that doesn't make sense and I'll add more detail.

**Comment by bradmartin** [comment]
The above solution hooking into page events should fix the issue.
