### ISSUE TITLE
error~

### ISSUE THREAD

**Issue by keepCreate** [bradmartin/nativescript-videoplayer#70]
Although you have update it to 3.0,but when i try it ,it show me that can't read property getSurfaceTexture of undefined , and i don't konw why,please help me ,thanks!

**Comment by bnussey** [comment]
Hey @keepCreate sorry about that, will need to do further testing. This is working with 3.0 https://github.com/NathanaelA/nativescript-exoplayer if you urgently need video, otherwise will resolve this tomorrow.

**Comment by bnussey** [comment]
Hey @keepCreate just published a fix.. can you give that a shot? Let me know thanks.

**Comment by keepCreate** [comment]
@bnussey 
![error](https://cloud.githubusercontent.com/assets/17747538/25879446/5ffc2f42-3564-11e7-9f51-9ffd98907460.png)

**Comment by keepCreate** [comment]
@bnussey of course.I have removed the old version and add the latest,and the error is same...  I don't know why...

**Comment by bnussey** [comment]
Ok just released 3.0.2 .. give that a shot.

**Comment by keepCreate** [comment]
@bnussey Thank you very much! It's work fine！And I want to develop a live streaming, do you have some suggestions?
