### ISSUE TITLE
nativescript-videoplayer not working on Android

### ISSUE THREAD

**Issue by conekeo** [bradmartin/nativescript-videoplayer#72]
Hi,
using "nativescript-videoplayer": "^3.0.3",
I got a weird bug, the plugin is working on IOS emulator, but nothing appear on Android (I'm using android genimotion emulator)

```
<VideoPlayer
      src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
      autoplay="true" 
      height="300"></VideoPlayer>
```
in the console I see:

`JS: Openvideo https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4`

any idea, did I missed an android setting?

Chuck

**Comment by bradmartin** [comment]
Can you share a screenshot of what you see? Since you have `autoplay=true` it should start the video. I haven't been involved much with NS 3+ yet and @bnussey has been doing the upgrade to 3.0 for this plugin - maybe he has some insight. Thanks for reporting your issue 😄

**Comment by conekeo** [comment]
I have no screenshot for Android because the space is blank/empty where I put the <VideoPlayer> directive.

**Comment by conekeo** [comment]
Update: When I try a local video it's working, but not remote file!
``` 
WORKING!
 <VideoPlayer
        src="~/videos/big_buck_bunny.mp4"
        autoplay="true" 
        height="250">
      </VideoPlayer>

```

**Comment by bradmartin** [comment]
That should help narrow down the cause, thanks for confirming local videos work.

**Comment by rialdi** [comment]
Hi @bradmartin  

I have the same issue here and i cannot play local videos either.
The plugin is working on iOS device but not working on Android Version 4.4.2

**Comment by 3rror404** [comment]
Same problem here. Neither local or remote files play on Android. Just an empty space and `Open video ...` in the console.

```
{N} : 3.0.3
nativescript-videoplayer : 3.0.7
Android : 6.0.1 
```

**Comment by bradmartin** [comment]
Just cleaned up the demo project - about to push some small changes but everything works on my phone (Android 7.1) geny emulator with 4.4, 5.1, 6.0, and 7+

Might be something locally in your projects, causing an issue. Does anyone have a sample repo to look at?

![video demo](https://user-images.githubusercontent.com/6006148/27052941-1e2cc2d4-4f81-11e7-9bc3-0cf1a4ae5f73.gif)

**Comment by 3rror404** [comment]
Hi @bradmartin,

here is a demo project using the latest plugin version: https://github.com/3rror404/NVideoPlayerIssue72

Some screenshots of what I see on iOS and Android below. If the empty space is tapped, the video loads.

![screenshot_20170613-102626](https://user-images.githubusercontent.com/1102402/27075812-3684cf28-5023-11e7-8905-ebe9bdec6245.png)
![simulator screen shot 13 jun 2017 10 26 33](https://user-images.githubusercontent.com/1102402/27075813-3689e9f4-5023-11e7-8068-2f874e5cf0de.png)

**Comment by debargho24-AI** [comment]
https://github.com/debargho24-AI/ng-ns-video-player -- Check out this link, it may solve the issue.
