### ISSUE TITLE
muted attribute changes not being honoured

### ISSUE THREAD

**Issue by svanderw** [bradmartin/nativescript-videoplayer#73]
I'm using version 2.6.1. (Not sure if there's a later npm which isn't 3.0.* yet, the latest doesn't work in my project yet)
It seems like when I use a data binding for whether or not the video should be muted, that the VideoPlayer isn't respecting the change on the property.  (I'm thinking that it's coming in as undefined, then after the videoplayer is initialized it's being switched to true or false)

ie the content of my template is
<StackLayout>
    <VideoPlayer #videonode src="{{videoData.videoURL}}" autoplay="true" [muted]="muted" [width]="videoWidth" [height]="videoHeight"></VideoPlayer>
</StackLayout>

if I switch to using 
muted="true" 
it started muted as expected.

**Comment by bnussey** [comment]
There is a mute method you can call if you want to mute/unmute. Check readme. 

**mute(boolean) - Mute the current video**

**Comment by bradmartin** [comment]
@svanderw - If you would like to create a PR to expose the property change event that would be great.
For a headstart see how the `src` propertyChange is set up here: https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer-common.ts#L56

**Comment by bnussey** [comment]
Yes thats a good point @bradmartin .. actually with the changes in NativeScript 3.0 property system this would be very easy to do.
