### ISSUE TITLE
finished event not firing

### ISSUE THREAD

**Issue by jibon57** [bradmartin/nativescript-videoplayer#74]
Hello,

I am trying with angularjs but don't know whey none of the Properties event not firing.

`<VideoPlayer #video playbackReady="{{videoReady}}"  finished="videoFinish()" src="{{videoSrc}}" autoplay="true" height="300"></VideoPlayer>`

I can set the src but can't get finished or any other events. Parts of TS code.

```
import { Video } from "nativescript-videoplayer";
import { registerElement } from "nativescript-angular/element-registry";
registerElement("VideoPlayer", () => require("nativescript-videoplayer").Video);

export class VideoComponent {

    @ViewChild("video") public video: ElementRef;
    private videoPlayer: Video;

ngAfterViewInit() {
        this.videoPlayer = this.video.nativeElement;
    }
public videoFinish(args) {
        console.log("Yes Finished");
    }
```
Any idea where I am doing wrong... Thanks in advance.

**Comment by bnussey** [comment]
In Angular you need to do it like this:

`(finished)="videoFinish()"`

**Comment by aaayushsingh** [comment]
@wanpeng2008 you can also use (finishedEvent)="videoFinish()" instead. 
`finished` isn't fired because its's not an event, `finishedEvent` is.

**Comment by alereisan** [comment]
the correct angular way is:
(finishedEvent)="videoFinish($event)"

dont forget the $event
