### ISSUE TITLE
Creating a Video element with JavaScript

### ISSUE THREAD

**Issue by 3rror404** [bradmartin/nativescript-videoplayer#75]
I'm trying to create a Video element and add it to a StackLayout with JavaScript but I don't seem to be able to configure all of the properties.

```
var videoPlayer = require("nativescript-videoplayer");

exports.tapVideoThumb = function(args) {
    const context = args.view.bindingContext;
    const listItem = args.object.parent; // StackLayout

    const videoElement = new videoPlayer.Video();
    videoElement.src = 'https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4';
    videoElement.height = 250;
    videoElement.controls = true;

    listItem.addChild(videoElement);
}
```

The above adds a Video element to the layout with the correct src but it has no controls and the height is ignored (see screenshot). 

What is the correct way to do this?

![video-issue](https://cloud.githubusercontent.com/assets/1102402/26053493/f3821f42-3960-11e7-8345-27682267e263.jpg)

```
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.5.5           │ 3.0.1          │ Update available │
│ tns-core-modules │ 2.5.2           │ 3.0.0          │ Update available │
│ tns-android      │                 │ 3.0.0          │ Not installed    │
│ tns-ios          │ 2.5.0           │ 3.0.0          │ Update available │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘
```

**Comment by 3rror404** [comment]
It seems I can turn on the controls on iOS using `videoElement._playerController.showsPlaybackControls = true;` but I cant see how to set the height of the player.

**Comment by bradmartin** [comment]
@3rror404 - this seems to work on android https://github.com/bradmartin/nativescript-videoplayer/blob/master/demo/app/main-view-model.ts#L118 could you confirm iOS?

**Comment by bradmartin** [comment]
Granted there might be some layout issues with native view rendering that will vary on iOS and Android. For example you may need to set a fixed height for iOS on the parent layout.

**Comment by 3rror404** [comment]
Hi @bradmartin,

I don't have my original project to test with as I ended up ditching this approach, but after a quick test in an empty project it looks to be working fine. 

Except autoplay doesn't work on iOS. Not sure if this is a limitation of the platform?

**Comment by bradmartin** [comment]
Possibly because it works fine on Android so I assume the js and NS pieces are working. So probably some iOS timing or behavioral issue. So if you try on iOS maybe use a `setTimeout()` with 100 or so ms and see what happens.

**Comment by bnussey** [comment]
Autoplay seems to work fine for me on iOS..
