### ISSUE TITLE
Excessive logging on iOS

### ISSUE THREAD

**Issue by RobertGardner** [bradmartin/nativescript-videoplayer#76]
(I love the player, by the way. Thanks!!!)

After playing a video with this player on iOS emulator, there is excessive logging to the console of the form:
    [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0

Destroying the video player does not stop the logging.

This logging is quite annoying and interferes with development.

Apparently it can be turned off by setting the environment variable OS_ACTIVITY_MODE=”disable” but I can't figure out how to get that environment variable into the emulator. The instructions I find on StackOverflow all assume development using XCode and give instructions on how to set it from the XCode UI.

I am using OSX 10.12.5 and XCode 8.3.3.

**Comment by bradmartin** [comment]
Yea this is annoying for sure. Nothing I'm aware of we can do at this
plugin level. It is an xcode iOS type issue. If you find some way to
disable it programmatically let me know

**Comment by RobertGardner** [comment]
Found a way to fix this!

Run this in your shell before running `tns run ios`:
```
export SIMCTL_CHILD_OS_ACTIVITY_MODE="disable"
```

**Comment by bradmartin** [comment]
Awesome Robert. Wanna PR that info to the readme? Very useful, not the
first time someone has brought this up with iOS apps :)
