### ISSUE TITLE
Can't play video (Android)

### ISSUE THREAD

**Issue by simplec-dev** [bradmartin/nativescript-videoplayer#80]
We've been using this plugin for 2 months in 2 different apps.

Something changed about 2 weeks ago in our dev environments.  Our apps don't play videos anymore.  I have the same problem with the demo project.

I assume(d) that it is something we did, but I can't figure it out.  We reinstalled nativescript.  We reinstalled Android SDK.  We downgraded nativescript versions.  Nothing seems to work.

So - I know we are probably doing something dumb.  I just don't know what. 

In the demo app, the video never loads.  So it won't play.  It won't get a duration.  It doesn't take up screen space.

I added logging to videoplayer.android.js.  Video.prototype.initNativeView is never called.

Any clues would be greatly appreciated.

**Comment by bnussey** [comment]
Is it local or remote video?

**Comment by bradmartin** [comment]
I just tried the demo and yea the video isn't playing. Really weird, last push I tested and all was fine. Not sure what happened. Will need some debugging to see what's happened.

**Comment by simplec-dev** [comment]
Well, I hate to say it but I'm glad.  We've been banging our heads against a wall for 3 days trying to figure out what we did.  Thanks for looking at it.

BTW - it is for local and remote.

**Comment by bradmartin** [comment]
Yea it's not rendering so I imagine it's no initializing.

**Comment by bradmartin** [comment]
@simplec-dev - have you tried NS 3.0 with the latest release of the plugin? Also can or have you tried different variations of NS with the latest release? I don't have time right now to figure out what changed to cause the issue so hopefully you can narrow it down to when it worked and what versions you have everything and we can find out. The last release I know I tested on android and iOS before publishing and the demo worked. So I'm guessing something in the core but of course that's a guess so possibly wrong. Lets just get different variations tested of core and this plugin to find when it last worked okay and then we can possibly ping the core team and see if they have someone to help debug it. I would but super low on free time this week and next :)

**Comment by simplec-dev** [comment]
It was definitely working with NS3.0 / Angular.  Both of our apps are angular.

We upgraded to 3.1.1 around the time that this started because of an update to Telerik Pro UI plugins.  My first thought was that it was the problem.  Yesterday we uninstalled nativescript and installed 3.0.1 on a machine.  We also reverted the package.json so the version numbers were downgraded.  We still had the same problem.

We have one app that was style NS2.x.  When that was built, local video didn't work either.

My gut says it is something in core modules.  But, I'm relatively new to nativescript and haven't developed many plugins.  So it is just instinct based on other experience.

**Comment by bradmartin** [comment]
@NickIliev - any chance you have a minute to look into this. The demo worked when I released 3.0.8 of this plugin with the current NS version at that time, about 24 days ago. Think that was 3.0.1. Really curious if you can get the demo to run or know of anything that changed that might cause an issue with the video not initializing.

**Comment by bnussey** [comment]
Just checked my android instance, not working for me either

**Comment by NathanaelA** [comment]
When I downgraded tns core modules to 3.01 the video player started working again.  Something in 3.1.0 breaks this and the exoplayer plugin.    

`npm remove tns-core-modules --save`
`npm install tns-core-modules@3.0.1 --save`

I'm also running the 3.0x runtimes; 3.1 should be compatible with 3.0 but it was my first test to see if it was the runtimes causing the issue.  Then I did the core modules...

**Comment by manijak** [comment]
I can confirm this. Android-only issue. iOS works fine on latest core-modules.

**Comment by NickIliev** [comment]
@bradmartin indeed the demo is not working with the latest `tns-core-modules` version. From the error I have received, it appears that `this.mediaPlayer` has value of `null`

**Comment by manijak** [comment]
Think I have a similar issue in mu Carousel plugin. After upgrading to 3.1.x all those new `setNative` properties are failing, all values are `undefined`.

**Comment by bradmartin** [comment]
Yea @nickilliev I think this is a bigger issue than just the video demo :(
I'll try to look into it today

**Comment by NathanaelA** [comment]
@NickIliev - Just another datapoint.  3.1 also break the NS-exoplayer plugin on android...  3.0 works fine.

**Comment by bradmartin** [comment]
@simplec-dev - until the core-modules issue is pinpointed and we figure this out try downgrading the core-modules as mentioned ^^^

**Comment by simplec-dev** [comment]
Thanks Brad.  I can't downgrade because of a ng-template bug that got fixed.  Apps are in a long QA cycle and we can avoid video for a while.  Thanks again.

**Comment by bradmartin** [comment]
@simplec-dev think I know the issue, will publish fix once confirmed and provide details and then go beat up @bnussey

**Comment by bradmartin** [comment]
Sorry to bother you on this one @NickIliev - the source for the android plugin had `initNativeView` and not `createNativeView` also not returning the native view instance. At any rate it did work with 3.0 so something changed to cause it to fail with 3.1 but at any rate the plugin has been fixed with version 3.0.9 @simplec-dev please check it out and let me know if you still have any issues. The demo works fine so I'm assuming all good to go now 😄

**Comment by simplec-dev** [comment]
Our apps have functional video again.  Thanks Brad.

**Comment by bnussey** [comment]
Nice one @bradmartin

**Comment by bradmartin** [comment]
@bnussey in california right? need a good excuse to visit 😆

**Comment by bnussey** [comment]
Yeah mate in LA! Always welcome to visit, as long as it isn't to beat me up haha ;)
