### ISSUE TITLE
Is it possible to Google Cast video?

### ISSUE THREAD

**Issue by nrbn** [bradmartin/nativescript-videoplayer#82]
I want to streaming video to a TV or bigger screen with google cast. Is it possible to do ?

Look at this link, this is what i want: [https://developers.google.com/cast/](url)

**Comment by bradmartin** [comment]
I haven't looked at the link but it it's possible with the Android APIs
used in the plugin source then yes. If it's a different Android API then
probably not with this plugin and a different approach is required.

**Comment by nrbn** [comment]
Screen cast using android sdk:
- 'com.google.android.gms:play-services-cast:9.4.0'
- 'com.android.support:mediarouter-v7:23.0.1'

But i could not get working with this plugin. Do you have any documentation for how to do it?

**Comment by bradmartin** [comment]
Sorry I don't. I imagine if you Google how to use those classes you'll find
examples from Google and you can view any of my plugins as a examples on
how to call the native APIs if you want to make a plugin. If you don't want
to do a plugin you can add those deps with Gradle and call it directly from
your app source code.

**Comment by nrbn** [comment]
Thank you bradmartin.
