### ISSUE TITLE
Audio file

### ISSUE THREAD

**Issue by kefahB** [bradmartin/nativescript-videoplayer#88]
Hello,
I search for a audio player (mp3...), there is some possibility for play audio file with this videoplayer ?

There is nativescript-audio but is not professionnel.

Thanks :-)

**Comment by bradmartin** [comment]
I think you want this plugin https://github.com/bradmartin/nativescript-audio

**Comment by 7ammer** [comment]
Nativescript-audio unfortunately requires the full mp3 file to be downloaded before it plays on IOS

**Comment by JonLevy** [comment]
I'm curious whether this has a resolution.  Can streaming audio be played through the video player?
