### ISSUE TITLE
It's possible to catch stream from UDP ? 

### ISSUE THREAD

**Issue by mabelanski** [bradmartin/nativescript-videoplayer#9]
Hi

Good job with your plugin 
Can you think that's possible to read stream from UDP ? 

Thanks

**Comment by bradmartin** [comment]
Hi @mabelanski - I don't know to be honest. Never used a UDP stream. If this is supported by iOS and Android within their native video player widgets then it would work. There could be a few changes necessary to make it happen but I have not looked into this.

**Comment by bradmartin** [comment]
Going to close this since it's not an "issue" but a question about native ability of android and iOS video players. If they support playing video natively with the video player widgets/controls then this will work, if not then it will not work. Thanks for your question.
